Repository harusari-chainware/harusari-chainware-vue, pull requests merged in 2025-07, with the labels that each got.

#7 refactor: 사이드바의 활성화 상태 구조 개선
  src/components/layout/LayoutDefault.vue
  src/components/layout/sidebar/SidebarItemList.vue
  src/constants/activeSidebarMap.js
  src/features/order/router.js
Labels: ♻️ 리팩토링

#9 ci: PR 자동 리뷰어 및 어싸인 등록 기능 구현
  .github/workflows/pr-auto-assign.yml
Labels: 🔗 ci/cd

#11 feat: 목록 조회 페이지를 위한 공통 레이아웃 ListLayout 구현
  package-lock.json
  package.json
  src/assets/css/_table.css
  src/assets/css/filter-common.css
  src/assets/css/flatpickr-custom.css
  src/assets/css/global.css
  src/assets/css/variables.css
  src/components/common/EmptyResult.vue
  src/components/common/GenericTable.vue
  src/components/common/Pagination.vue
  src/components/common/SkeletonList.vue
  src/components/common/StatusBadge.vue
  src/components/common/filters/FilterButtons.vue
  src/components/common/filters/FilterDate.vue
  src/components/common/filters/FilterDateRange.vue
  src/components/common/filters/FilterSearchModal.vue
  src/components/common/filters/FilterSelect.vue
  src/components/common/filters/FilterText.vue
  src/components/common/top-actions/CreateButton.vue
  src/components/common/top-actions/SortDropdown.vue
  src/components/common/top-actions/SortOrderSelect.vue
  src/components/layout/Header.vue
  src/components/layout/LayoutDefault.vue
  src/components/layout/ListLayout.vue
  src/components/layout/Sidebar.vue
  src/components/layout/listview/ListFiltersSection.vue
  src/components/layout/listview/ListTableSection.vue
  src/components/layout/listview/ListTopActions.vue
  src/components/layout/sidebar/SidebarGroup.vue
  src/components/layout/sidebar/SidebarItemList.vue
  src/constants/activeSidebarMap.js
  src/constants/dummy/order.js
  src/features/order/components/OrderFilters.vue
  src/features/order/components/OrderTable.vue
  src/features/order/components/component.vue
  src/features/order/router.js
  src/features/order/views/OrderListView.vue
  src/main.js
  src/utils/tableUtils.js
Labels: 🤖 기능

#13 feat: 상세 조회 페이지를 위한 공통 레이아웃 DetailLayout 구현
  src/assets/css/global.css
  src/assets/css/variables.css
  src/components/common/SkeletonDetail.vue
  src/components/common/SkeletonItem.vue
  src/components/common/StatusButton.vue
  src/components/common/filters/FilterButtons.vue
  src/components/common/top-actions/CreateButton.vue
  src/components/layout/DetailLayout.vue
  src/components/layout/detailview/DetailTable.vue
  src/components/layout/detailview/DetailTableMoreLink.vue
  src/components/layout/detailview/DetailTablePagination.vue
  src/components/layout/detailview/InfoGroup.vue
  src/components/layout/detailview/InfoItem.vue
  src/constants/dummy/orderDetail.js
  src/features/order/components/OrderDetailBasic.vue
  src/features/order/components/OrderDetailBasicInfo.vue
  src/features/order/components/OrderDetailDate.vue
  src/features/order/components/OrderDetailDeliveryHistory.vue
  src/features/order/components/OrderDetailDetail.vue
  src/features/order/components/OrderDetailFranchise.vue
  src/features/order/components/OrderDetailRejectReason.vue
  src/features/order/components/OrderDetailSummary.vue
  src/features/order/components/OrderTable.vue
  src/features/order/router.js
  src/features/order/views/OrderDetailView.vue
  src/features/order/views/OrderListView.vue
Labels: 🤖 기능

#15 feat: 로그인 페이지 구현
  package-lock.json
  package.json
  src/components/layout/login/AuthLayout.vue
  src/features/auth/api.js
  src/features/auth/router.js
  src/features/auth/useAuthStore.js
  src/features/auth/views/login/LoginView.vue
  src/features/member/router.js
  src/main.js
  src/router/index.js
Labels: 🤖 기능

#20 feat: 등록 페이지를 위한 공통 레이아웃 RegisterLayout 구현
  src/assets/css/variables.css
  src/components/common/GenericSearchButton.vue
  src/components/common/GenericSearchTable.vue
  src/components/common/GenericSearchWrapper.vue
  src/components/common/fields/AddressSearchField.vue
  src/components/common/fields/DatePickerField.vue
  src/components/common/fields/FileUploadField.vue
  src/components/common/fields/InputField.vue
  src/components/common/fields/ReadonlyField.vue
  src/components/common/fields/SearchFieldWithButton.vue
  src/components/common/fields/SearchReadonlyGroup.vue
  src/components/common/fields/SelectField.vue
  src/components/common/fields/TextareaField.vue
  src/components/layout/RegisterLayout.vue
  src/components/layout/registerview/RegisterDetailTable.vue
  src/components/layout/registerview/RegisterFooter.vue
  src/components/layout/registerview/RegisterInfoGroup.vue
  src/components/layout/registerview/RegisterLeftSection.vue
  src/components/layout/registerview/RegisterRightPanel.vue
  src/components/layout/registerview/RegisterSummaryBox.vue
  src/constants/dummy/orderRegister.js
  src/constants/dummy/orderSearchTableConfig.js
  src/features/category/views/CategoryListView.vue
  src/features/member/router.js
  src/features/order/components/OrderDetailBasic.vue
  src/features/order/components/OrderRegisterDetail.vue
  src/features/order/components/OrderRegisterFooter.vue
  src/features/order/components/OrderRegisterLeft.vue
  src/features/order/components/OrderRegisterRightPanel.vue
  src/features/order/components/detailview/OrderDetailBasicInfo.vue
  src/features/order/components/detailview/OrderDetailDate.vue
  src/features/order/components/detailview/OrderDetailDeliveryHistory.vue
  src/features/order/components/detailview/OrderDetailFranchise.vue
  src/features/order/components/detailview/OrderDetailRejectReason.vue
  src/features/order/components/detailview/OrderDetailSummary.vue
  src/features/order/components/registerview/OrderRegisterApproverInfo.vue
  src/features/order/components/registerview/OrderRegisterOrderInfo.vue
  src/features/order/components/registerview/OrderRegisterStoreInfo.vue
  src/features/order/components/registerview/OrderRegisterVendorSearch.vue
  src/features/order/router.js
  src/features/order/views/OrderRegisterView.vue
  src/router/index.js
Labels: 🤖 기능

#28 feat: 회원 상세 페이지 기능 구현
  src/api/axios.js
  src/components/common/filters/FilterDateRange.vue
  src/features/auth/useAuthStore.js
  src/features/auth/views/login/LoginView.vue
  src/features/member/api.js
  src/features/member/master/components/DetailRow.vue
  src/features/member/master/components/MemberDetailBasic.vue
  src/features/member/master/components/MemberLoginHistory.vue
  src/features/member/master/components/MemberTable.vue
  src/features/member/master/views/MemberDetailView.vue
  src/features/member/master/views/MemberListView.vue
  src/features/member/router.js
  src/router/index.js
  src/utils/jwt.js
Labels: ♻️ 리팩토링, 🤖 기능

#30 refactor: Pagination 설정 변경
  src/components/common/Pagination.vue
Labels: ♻️ 리팩토링

#32 refactor: 사이드바 메뉴 아이콘 적용
  src/components/layout/Header.vue
  src/components/layout/sidebar/SidebarItemList.vue
  src/constants/sidebarMap.js
  src/features/category/views/CategoryListView.vue
  src/features/member/router.js
Labels: ♻️ 리팩토링

#34 feat: 회원 정보 수정 기능 구현
  src/features/member/api.js
  src/features/member/master/components/MemberDetailBasic.vue
  src/features/member/master/views/MemberDetailView.vue
  src/features/member/master/views/MemberListView.vue
Labels: 🤖 기능

#43 feat: 회원 마이페이지 기능 구현
  src/components/layout/Header.vue
  src/constants/sidebarMap.js
  src/features/member/api.js
  src/features/member/master/components/MemberDetailBasic.vue
  src/features/member/mypage/views/ChangePasswordView.vue
  src/features/member/mypage/views/MyProfileView.vue
  src/features/member/router.js
Labels: 🤖 기능

#48 feat: 폐기 등록 및 조회
  src/components/layout/Header.vue
  src/constants/sidebarMap.js
  src/features/disposal/api.js
  src/features/disposal/components/DisposalTable.vue
  src/features/disposal/components/NormalDisposalForm.vue
  src/features/disposal/components/RecentDisposalTable.vue
  src/features/disposal/components/TakebackDisposalForm.vue
  src/features/disposal/router.js
  src/features/disposal/views/AdminDisposalView.vue
  src/features/disposal/views/DisposalRegisterView.vue
  src/features/statistics/components/PredictionAccuracyDashboard.vue
  src/features/statistics/components/PredictionComparisonDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
Labels: 🤖 기능

#50 fix: 탭 버튼과 조회 버튼을 빠르게 누르면 Chart가 안나오는 오류 수정
  getDisposal.html
  postdisposal.html
  src/features/statistics/components/DisposalDashboard.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/MenuSalesDashboard.vue
  src/features/statistics/components/PredictionAccuracyDashboard.vue
  src/features/statistics/components/PredictionComparisonDashboard.vue
  src/features/statistics/components/PurchaseOrderDashboard.vue
  src/features/statistics/components/StoreOrderDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
Labels: 🔨 수정

#54 fix: 가맹점/거래처 담당자 등록 시 연락처·사업자번호 하이픈 제거 및 FormData 전송 구조 통일
  src/features/member/master/views/MemberRegisterView.vue
Labels: 🐞 버그

#56 fix: 거래처 회원 등록이 안되는 문제 해결
  src/features/member/master/components/join/VendorForm.vue
  src/features/member/master/views/MemberRegisterView.vue
Labels: 🐞 버그

#60 Fix: 통계 디자인 통일
  src/components/layout/Header.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/MenuSalesDashboard.vue
  src/features/statistics/components/PredictionAccuracyDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
Labels: 🔨 수정

#65 fix: Axios 인터셉터 무한 새로고침 방지 및 예외 처리 개선
  src/api/axios.js
Labels: 🐞 버그

#66 feat: 주문 관리 기능 구현
  src/features/order/api.js
  src/features/order/components/OrderTable.vue
  src/features/order/components/detailview/OrderDetailDate.vue
  src/features/order/components/detailview/OrderDetailDeliveryHistory.vue
  src/features/order/components/modal/OrderApproveModal.vue
  src/features/order/components/modal/OrderCancelModal.vue
  src/features/order/components/modal/OrderRejectModal.vue
  src/features/order/views/OrderDetailView.vue
  src/features/order/views/OrderRegisterView.vue
Labels: 🤖 기능

#74 refactor : 잘못된 주석 삭제 및 alert 알림 toast로 대체
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/assets/css/toast.css
  src/components/common/Pagination.vue
  src/components/common/fields/MemberSearchModal.vue
  src/features/category/components/CategoryForm.vue
  src/features/category/components/CategoryModal.vue
  src/features/disposal/views/AdminDisposalView.vue
  src/features/disposal/views/DisposalRegisterView.vue
  src/features/order/views/OrderListView.vue
  src/features/purchase/PurchaseApi.js
  src/features/purchase/components/PurchaseFilters.vue
  src/features/purchase/components/PurchaseOrderDetailDetail.vue
  src/features/purchase/views/PurchaseOrderDetailView.vue
  src/features/purchase/views/PurchaseOrderListView.vue
  src/features/requisition/components/Register/AutoCompleteField.vue
  src/features/requisition/components/Register/RequisitionRegisterFooter.vue
  src/features/requisition/components/Register/RequisitionSearchTable.vue
  src/features/requisition/components/RequisitionDetailWarehouse.vue
  src/features/requisition/components/RequisitionFilters.vue
  src/features/requisition/views/RequisitionDetailView.vue
  src/features/requisition/views/RequisitionListView.vue
  src/features/requisition/views/RequisitionRegisterView.vue
  src/features/statistics/components/DisposalDashboard.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/PredictionComparisonDashboard.vue
  src/features/statistics/components/StoreOrderDashboard.vue
  src/features/vendor/views/VendorDetailView.vue
  src/main.js
Labels: ♻️ 리팩토링

#76 ci: Vue.js S3 + CloudFront 배포 CI/CD 워크플로우 추가
  .github/workflows/s3-cloudfront-deploy.yml
Labels: 🔗 ci/cd

#78 refactor: axios baseURL 환경변수 제거 및 코드 상에 명시
  src/api/axios.js
Labels: ♻️ 리팩토링

#82 fix: 코드 수정
  src/components/layout/Header.vue
Labels: 🐞 버그

#84 refactor : 품의 / 발주 추가 기능 마무리
  src/components/common/RejectReasonModal.vue
  src/components/common/fields/DatePickerField.vue
  src/features/category/views/CategoryCreateView.vue
  src/features/purchase/PurchaseApi.js
  src/features/purchase/components/PurchaseFilters.vue
  src/features/purchase/views/PurchaseOrderDetailView.vue
  src/features/purchase/views/PurchaseOrderListView.vue
  src/features/requisition/RequisitionApi.js
  src/features/requisition/components/Register/RequisitionRegisterFooter.vue
  src/features/requisition/components/Register/RequisitionRegisterOrderInfo.vue
  src/features/requisition/components/Register/RequisitionRegisterRightPanel.vue
  src/features/requisition/router.js
  src/features/requisition/views/RequisitionDetailView.vue
  src/features/requisition/views/RequisitionListView.vue
  src/features/requisition/views/RequisitionRegisterView.vue
  src/main.js
Labels: ♻️ 리팩토링

#85 feat: 관리자 - 창고 재고 조회 페이지 구현
  getwarehouse.html
  src/components/common/filters/FilterDate.vue
  src/features/statistics/components/DisposalDashboard.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/PredictionAccuracyDashboard.vue
  src/features/statistics/components/PredictionComparisonDashboard.vue
  src/features/statistics/components/PurchaseOrderDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
  src/features/warehouse/api.js
  src/features/warehouse/components/InventoryDetailModal.vue
  src/features/warehouse/components/InventoryFilter.vue
  src/features/warehouse/components/InventoryTable.vue
  src/features/warehouse/router.js
  src/features/warehouse/views/InventoryView.vue
Labels: 🤖 기능

#87 feat: 권한에 따른 사이드바 분기 조회 기능 구현
  src/components/layout/LayoutDefault.vue
  src/components/layout/Sidebar.vue
  src/features/order/router.js
Labels: 🤖 기능

#89 refactor: 로그인 시 권한별 페이지 이동 기능 구현
  public/chainware-logo-circle.ico
  public/favicon.ico
  src/features/auth/views/login/LoginView.vue
Labels: ♻️ 리팩토링

#93 feat: 반품 목록, 상세 조회 페이지 구현
  getwarehouse.html
  src/api/axios.js
  src/features/statistics/components/DisposalDashboard.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
  src/features/takeback/api.js
  src/features/takeback/components/InfoCard.vue
  src/features/takeback/components/ProductTable.vue
  src/features/takeback/components/TakeBackFilter.vue
  src/features/takeback/components/TakeBackList.vue
  src/features/takeback/components/TakeBackTable.vue
  src/features/takeback/router.js
  src/features/takeback/views/TakeBackDetailView.vue
  src/features/takeback/views/TakeBackListView.vue
Labels: 🤖 기능

#97 refactor : 품의 등록 시 거래처별 계약 품목 조회 오류 수정
  src/api/axios.js
  src/features/category/views/CategoryDetailView.vue
  src/features/category/views/TopCategoryDetailView.vue
  src/features/product/views/ProductDetailView.vue
  src/features/requisition/components/Register/RequisitionRegisterDetail.vue
  src/features/requisition/components/Register/RequisitionRegisterDrafterInfo.vue
  src/features/requisition/components/Register/RequisitionRegisterLeft.vue
  src/features/requisition/components/Register/RequisitionRegisterRightPanel.vue
  src/features/requisition/components/Register/RequisitionSearchTable.vue
  src/features/requisition/views/RequisitionRegisterView.vue
Labels: ♻️ 리팩토링

#113 fix: 차트 랜더링 오류 수정
  src/api/axios.js
  src/features/statistics/components/DisposalDashboard.vue
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/statistics/components/MenuSalesDashboard.vue
  src/features/statistics/components/PurchaseOrderDashboard.vue
  src/features/statistics/components/TotalSalesDashboard.vue
Labels: 🔨 수정

#115 fix: 거래처 조회, 헤더, 사이드바 수정
  src/components/layout/Header.vue
  src/components/layout/LayoutDefault.vue
  src/constants/sidebarMap.js
  src/features/auth/views/login/LoginView.vue
  src/features/category/components/CategoryTable.vue
  src/features/category/views/TopCategoryDetailView.vue
  src/features/contract/views/ContractCreateView.vue
  src/features/product/views/ProductCreateView.vue
  src/features/vendor/views/VendorDetailView.vue
Labels: 🐞 버그

#117 refactor: 불필요한 alert 및 console 출력 제거
  src/components/layout/Header.vue
  src/features/auth/useAuthStore.js
  src/features/auth/views/login/LoginView.vue
  src/features/member/master/views/MemberListView.vue
Labels: ♻️ 리팩토링

#118 feat: 주문에 대한 시각적 요소 개선
  src/features/order/components/modal/OrderApproveModal.vue
  src/features/order/components/modal/OrderRejectModal.vue
  src/features/order/views/OrderDetailView.vue
  src/features/order/views/OrderListView.vue
  src/features/order/views/OrderRegisterView.vue
  src/features/takeback/components/TakeBackList.vue
Labels: ♻️ 리팩토링

#122 fix: 반품 목록 조회
  src/features/takeback/api.js
  src/features/takeback/components/TakeBackFilter.vue
  src/features/takeback/components/TakeBackList.vue
  src/features/takeback/views/TakeBackListView.vue
Labels: 🔨 수정

#128 fix: 슈퍼 계정 반품 조회 2개 발생하는 문제 해결
  src/api/axios.js
  src/constants/sidebarMap.js
  src/features/delivery/components/modal/DeliveryStartModal.vue
  src/features/delivery/views/DeliveryDetailView.vue
  src/features/takeback/components/TakeBackMyList.vue
  src/features/takeback/views/TakeBackMyListView.vue
  src/features/warehouse/components/InventoryFilter.vue
  src/features/warehouse/components/InventoryWarehouseFilter.vue
Labels: 🔨 수정

#130 fix: console.log 주석 처리
  src/api/axios.js
Labels: 🔨 수정

#132 fix: 드롭다운, 사이드바 수정
  src/constants/sidebarMap.js
  src/features/purchase/views/PurchaseOrderListView.vue
Labels: 🐞 버그

#134 fix: 창고 목록 조회와 재고 상세 모달에 안전재고 추가
  src/constants/sidebarMap.js
  src/features/statistics/components/InventoryTornoverDashboard.vue
  src/features/warehouse/components/InventoryDetailModal.vue
  src/features/warehouse/components/InventoryTable.vue
  src/features/warehouse/views/InventoryView.vue
Labels: 🔨 수정

#136 제품 및 거래처별 제품 계약 영문 → 한글 라벨 변경, 거래처 상세 페이지에 권한 기반 수정 버튼 노출 조건 적용
  src/features/contract/components/ContractForm.vue
  src/features/contract/components/ContractTable.vue
  src/features/contract/views/ContractCreateView.vue
  src/features/contract/views/ContractListView.vue
  src/features/product/components/ProductFilters.vue
  src/features/product/components/ProductTable.vue
  src/features/product/views/ProductCreateView.vue
  src/features/product/views/ProductDetailView.vue
  src/features/vendor/views/VendorDetailView.vue
Labels: ♻️ 리팩토링, 🤖 기능

#138 refactor: 반품 증빙 자료 코드 주석 처리
  src/features/takeback/views/TakeBackDetailView.vue
Labels: ♻️ 리팩토링

#140 fix: prediction_type에 일치하게 predictionType 수정
  src/features/statistics/components/PredictionAccuracyDashboard.vue
Labels: 🔨 수정
